### ISSUE TITLE
error

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Kodi_AppImage#1]
```
id: /tmp/.mount_Kodi-2C6T10J/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by id)
libEGL warning: DRI3: Screen seems not DRI3 capable
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so has no function __vaDriverInit_1_0
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so has no function __vaDriverInit_1_0
libva info: va_openDriver() returns -1
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so has no function __vaDriverInit_1_0
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so has no function __vaDriverInit_1_0
libva info: va_openDriver() returns -1
terminate called after throwing an instance of 'fmt::v6::format_error'
  what():  string pointer is null
Aborted
Crash report available at /home/thinker/kodi_crashlog-20230926_100547.log
```

**Comment by lucasmz1** [comment]
ok i will fix that!

thanks for your reply.

> ```
> id: /tmp/.mount_Kodi-2C6T10J/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by id)
> libEGL warning: DRI3: Screen seems not DRI3 capable
> libva info: VA-API version 1.7.0
> libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
> libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so has no function __vaDriverInit_1_0
> libva info: va_openDriver() returns -1
> libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
> libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so has no function __vaDriverInit_1_0
> libva info: va_openDriver() returns -1
> libva info: VA-API version 1.7.0
> libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
> libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so has no function __vaDriverInit_1_0
> libva info: va_openDriver() returns -1
> libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
> libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so has no function __vaDriverInit_1_0
> libva info: va_openDriver() returns -1
> terminate called after throwing an instance of 'fmt::v6::format_error'
>   what():  string pointer is null
> Aborted
> Crash report available at /home/thinker/kodi_crashlog-20230926_100547.log
> ```

**Comment by lucasmz1** [comment]
I will fix that.
thanks for reporting that!
